/**
 * A helper for loading remote javascript using the "script tag hack".
 * The <script> tags might fetch any (remote) javascript by specifying
 * a 'src' attribute - they are not constrained by the same origin policy
 * as AJAX requests.
 * Loading might be defered until DOM is ready using the 'onLoad' argument.
 * Besides there's special support for scripts that write directly to the
 * DOM using <code>document.write()</code>(e.g. GitHub's gist embedding).
 * These are handled properly (yes even if the script loading was defered)
 * and You might even modify the writen HTML content before it gets into
 * Your page.
 * 
 * @param args the arguments object or a string in which case it behaves
 * like if <code>{ src: args }</code> was specified as the function args
 *
 * Supported arguments/properties :
 * 
 * - src: the script source - absolute HTTP URL or relative to 'base',
 *   this is the only required property
 *
 * - base: the URL base - allows relative paths with the 'src' property
 *
 * - onLoad: set to true to load scripts after DOM is ready otherwise their
 *   going to load while building the DOM
 *
 * - order: the order of loading the scripts (makes sense only when onLoad is
 *   true), e.g. adding a script with order 0 means that it will get to the
 *   0-th position in the list of scripts to be loaded and thus will be loaded
 *   first
 *
 * - loadingHTML: HTML to show in place of the script while not loaded
 *
 * - loaded: callback that gets invoked after the script has loaded the script
 *   element is passed as the first param if the loading happened during
 *   or after DOM ready event (e.g. `onLoad: true`) and the loaded javascript
 *   called `document.write()/writeln()` the second parameter to the callback
 *   is a string array consisting of all the `write(str)` invocation arguments
 *
 * - append: where to append the <script> element, if it's a string an element
 *   with an id is searched and the script is appended as a child of that node,
 *   otherwise it should be a function that receives a script element and
 *   should inject the node into the DOM
 *
 * NOTE: that the location of the script element is crucial if other elements
 * or HTML using document.write() is generated by the executed (remote)
 * javascript - the new content gets after the script element in the DOM !
 *
 * To setup default arguments for script() use the defaults object :
 * <code>
 *   script.defaults.onLoad = true;
 *   script.defaults.base = 'http://gist.github.com';
 * </code>
 *
 * @author Copyright (c) 2010 - Karol Bucek
 * @license http://www.apache.org/licenses/LICENSE-2.0.html
 * @version 0.5
 */
var script = ( function() {
    var debug = false;
    var log = function() {}; // empty fn
    if (debug) {
        log = function() {
            if ( debug && typeof(console) !== 'undefined' ) {
                console.log(arguments);
            }
        }
    }
    var writes = null;
    var tempDocWrite = function() { // a document.write replacement
        var args = arguments;
        if ( args && args[0] ) {
            log('document.write() args[0] = ', args[0]);
            if ( ! writes ) writes = [];
            writes.push( args[0] );
        }
        else {
            log('document.write() unexpected args = ', args);
        }
    };
    var tempDocWriteln = function(str) { tempDocWrite(str + '\n'); };
    
    var docWrite, docWriteln; // original document.write / writeln
    function overrideDocWrites() {
        if ( ! docWrite ) docWrite = document.write;
        if ( ! docWriteln ) docWriteln = document.writeln;
        document.write = tempDocWrite;
        document.writeln = tempDocWriteln;
    }
    function restoreDocWrites() {
        if ( docWrite ) document.write = docWrite;
        if ( docWriteln ) document.writeln = docWriteln;
        docWrite = null; docWriteln = null;
    }

    // load the next "script" (element) and invoke callback when done :
    function loadScript(opts, doneCallback) {
        log('loadScript() opts = ', opts);
        var loadedCallback = opts.loaded, $script;
        
        if ( opts.onLoad ) {
            $script = document.createElement('script');
            $script.setAttribute('src', opts.src);

            var handleScriptLoaded = function() {
                if (loadedCallback) {
                    loadedCallback($script, writes || undefined);
                }
                var $div = document.getElementById(opts.id); // placeholder
                if ( writes ) { // document.write happened
                    log('handleScriptLoaded() writeArray.len = ', writes.length);
                    var $scriptSibling = $script.nextSibling;
                    // nodes should get after the <script> tag :
                    var appendNode = function($node) {
                        if ($scriptSibling) {
                            $script.parentNode.insertBefore($node, $scriptSibling);
                        }
                        else {
                            $script.parentNode.appendChild($node);
                        }
                    };
                    if ( ! $div ) { // if called after DOM load - it won't exist
                        $div = document.createElement('div');
                        appendNode( $div );
                    }
                    // insert the HTML collected from document.write :
                    $div.style.display = 'none';
                    $div.innerHTML = writes.join('');
                    // the HTML gets after the <script> tag :
                    while ( $div.childNodes[0] ) { // as NodeList is live
                        appendNode( $div.childNodes[0] );
                    }
                }
                if ( $div ) $div.parentNode.removeChild($div); // was a temporary
            };

            if ($script.readyState) { // IE
                $script.onreadystatechange = function() {
                    if ($script.readyState === "loaded" ||
                        $script.readyState === "complete") {
                        $script.onreadystatechange = null;
                        handleScriptLoaded();
                        if ( doneCallback ) doneCallback();
                    }
                };
            }
            else { // non-IE
                $script.onload = function() {
                    handleScriptLoaded();
                    if ( doneCallback ) doneCallback();
                };
            }
            opts.append($script); // finally a <script> gets into DOM
        }
        else {
            $script = document.getElementById(opts.id);
            if ( loadedCallback ) loadedCallback($script);
            if ( doneCallback ) doneCallback();
        }
    }
    // a custom list used to store args for which embedGist() has
    // been called (for later processing - when the DOM is ready)
    var scripts = []; // a list of scripts to load
    scripts.yieldNext = function(yield) {
        if ( ! this.next ) this.next = 0;
        log('yieldNext() next = ', this.next);
        var nextElem = this[ this.next++ ]; // the args
        if ( nextElem ) {
            yield( nextElem );
            return true; // yielded
        }
        else {
            log('yieldNext() no next - done !');
            return false; // no yield
        }
    };
    // load all stored gist elements by iterating with loadScript()
    function loadAllScripts() {
        if ( ! scripts ) return; // already loaded or nothing to load
        log('loadAllScripts() scripts.length = ', scripts.length);
        var _scripts = scripts; scripts = null;

        var loadAndYieldNext = function(opts) {
            overrideDocWrites();
            loadScript(opts, function() {
                restoreDocWrites(); writes = null; // clear for next
                _scripts.yieldNext(loadAndYieldNext); // recurse to next
            });
        };
        _scripts.yieldNext(loadAndYieldNext);
    }
    // initialization - after DOM is ready call loadAllScripts() :
    var loadFunc;
    if ( document.addEventListener ) {
        loadFunc = function() {
            document.removeEventListener("DOMContentLoaded", loadFunc, false);
            loadAllScripts(); loadFunc = null;
        };
        document.addEventListener("DOMContentLoaded", loadFunc, false);
     }
     else if ( document.attachEvent ) { // IE
        loadFunc = function() {
            if (document.readyState === "complete") { // make sure body exists
                document.detachEvent( "onreadystatechange", loadFunc );
                loadAllScripts(); loadFunc = null;
            }
        };
        document.attachEvent("onreadystatechange", loadFunc);
    }
    var uid = 0;
    var script = function(args) {
        if ( ! args ) throw 'script() no arguments given';
        if ( typeof(args) === "string" ) {
            args = { src: args };
        }
        else {
            if ( ! args.src ) throw "script() 'src' is required";
        }
        
        var name, opts = {}, defs = script.defaults;
        if ( defs ) for ( name in defs ) opts[name] = defs[name];
        for ( name in args ) opts[name] = args[name];
        // complete some of the provided arguments :
        if ( opts.base && opts.src.substring(0, 4) !== 'http' ) {
            var base = opts.base, last = opts.base.length - 1;
            base = base[last] == '/' ? base.substring(0, last) : base;
            opts.src = base + '/' + opts.src;
        }
        
        if ( opts.onload != null ) { // normalize onload -> onLoad
            if ( opts.onLoad != null ) {
                // make sure defs.onload does not overwrite args.onLoad :
                if ( args.onload != null ) opts.onLoad = args.onload;
                else if ( args.onLoad != null ) opts.onLoad = args.onLoad;
                else opts.onLoad = opts.onload;
            }
            else {
                opts.onLoad = opts.onload;
            }
            delete opts.onload;
        }
        
        if ( ! opts.id ) { // generate an id
            opts.id = '_script-' + ( uid++ );
        }
        
        var append = opts.append;
        if ( typeof(append) === "string" ) { // treat as Node ID
            opts.append = function($script) {
                var $elem = document.getElementById(append);
                $elem.appendChild($script);
            }
        }
        else if ( append && append.appendChild ) { // Node itself
            opts.append = function($script) { 
                append.appendChild($script);
            }
        }

        // loadFunc is null after DOM load event already occured :
        if ( loadFunc ) {
            var content = '';
            if ( opts.onLoad ) {
                content = '<div id="'+ opts.id +'"';
                if ( opts.loadingHTML ) content += ('>' + opts.loadingHTML);
                else content += ' style="diplay: none;">';
                content += '</div>'; // no <script> yet - only a <div>
                if ( ! opts.append ) {
                    opts.append = function(script) {
                        var $div = document.getElementById(opts.id);
                        $div.parentNode.insertBefore(script, $div);
                    }
                }
            }
            else {
                content = '<script id="'+ opts.id +'" src="'+ opts.src +'"><\/script>';
            }
            document.write(content); // ok as we're still building the DOM
            var order = opts.order;
            if (order == null) scripts.push( opts );
            else scripts.splice( order, 0, opts );
        }
        else { // DOM load already happened
            opts.onLoad = true; // doesn't make sense to be false
            if ( ! opts.append ) {
                opts.append = function(script) {
                    var $elem = document.getElementsByTagName('body')[0];
                    $elem.appendChild(script);
                }
            }
            overrideDocWrites();
            loadScript(opts, function() {
                restoreDocWrites();
                writes = null; // clear it for next iteration
            }); // immediately - onload already happened
        }
        //if ( scripts ) scripts.push( opts );
        //else loadScript(opts);
    }
    // default options :
    script.defaults = {};
    
    return script;
    
})();